USE Test_Live_Data
GO

SET ANSI_NULLS ON
 SET QUOTED_IDENTIFIER ON;

WITH CTE AS (
SELECT 
	[respParent],
	FMH_ES_Campus_Code,
	FMH_ES_CCS_Ref_Rec,
	FMH_ES_CCS_Office_Ref,
	FMH_ES_MHARS_Assess,
	FMH_ES_AMHS,
	FMH_ES_Screen_Outcome,
	FMH_ES_Assess_Outcome,
	FMH_ES_CA_to_CCS,
	FMH_ES_MH_Cond_1,
	FMH_ES_MH_Cond_2,
	FMH_ES_MH_Cond_3,
	FMH_ES_MH_Cond_4,
	FMH_ES_MH_Cond_5,
	FMH_ES_HONOS_START,
	FMH_ES_HONOS_END,
	FMH_ES_TOB_COM,
	FMH_ES_TOB_END,
	FMH_ES_End_Date,
	FMH_ES_Dis_Reason

FROM 
(
	SELECT SQ.qName, SR.respParent, SR.respValue 
	FROM dbo.SurveyResponses SR WITH (NOLOCK)
	INNER JOIN dbo.SurveyQuestions SQ WITH (NOLOCK) ON SQ.qID = SR.qID AND SQ.qMasterQuestionID IS NULL
	INNER JOIN dbo.Surveys S WITH (NOLOCK) ON SQ.svyID = S.svyID AND S.svyName = 'FMH Episode of Service' 
) SV
PIVOT
(
MAX(respValue)
FOR qName IN (
	FMH_ES_Campus_Code,
	FMH_ES_CCS_Ref_Rec,
	FMH_ES_CCS_Office_Ref,
	FMH_ES_MHARS_Assess,
	FMH_ES_AMHS,
	FMH_ES_Screen_Outcome,
	FMH_ES_Assess_Outcome,
	FMH_ES_CA_to_CCS,
	FMH_ES_MH_Cond_1,
	FMH_ES_MH_Cond_2,
	FMH_ES_MH_Cond_3,
	FMH_ES_MH_Cond_4,
	FMH_ES_MH_Cond_5,
	FMH_ES_HONOS_START,
	FMH_ES_HONOS_END,
	FMH_ES_TOB_COM,
	FMH_ES_TOB_END,
	FMH_ES_End_Date,
	FMH_ES_Dis_Reason
)
) as PVT
WHERE PVT.respParent IS NOT NULL
)

SELECT
	CTE.FMH_ES_Campus_Code AS CAMPUS_CODE,
	Programs.pgCode AS EPISODE_IDENTIFIER,
	Episode.epUR AS CAMPUS_CLIENT_ID,
	ISNULL(REPLACE(CONVERT(VARCHAR, cte.FMH_ES_CCS_Ref_Rec,103),'/',''), '') AS DATE_CCS_REFERRAL_RECEIVED,
	cte.FMH_ES_CCS_Office_Ref AS REFERRING_CCS_OFFICE,
	ISNULL(cte.FMH_ES_MHARS_Assess,'') AS MHARS_ASSESSMENT_FLAG,
	cte.FMH_ES_AMHS AS STEP_DOWN_FROM_AMHS_FLAG,
	ISNULL(cte.FMH_ES_Screen_Outcome, 8) AS SCREENING_OUTCOME,
	ISNULL(cte.FMH_ES_Assess_Outcome, 8) AS COMPREHENSIVE_ASSESSMENT_OUTCOME,
	ISNULL(REPLACE(CONVERT(VARCHAR, cte.FMH_ES_CA_to_CCS,103),'/',''),'') AS DATE_COMPREHENSIVE_REFERRAL_SENT_TO_CCS,
	ISNULL(cte.FMH_ES_MH_Cond_1, 'Z71.1') AS MENTAL_HEALTH_CONDITION_1,
	ISNULL(cte.FMH_ES_MH_Cond_2, '') AS MENTAL_HEALTH_CONDITION_2,
	ISNULL(cte.FMH_ES_MH_Cond_3, '') AS MENTAL_HEALTH_CONDITION_3,
	ISNULL(cte.FMH_ES_MH_Cond_4, '') AS MENTAL_HEALTH_CONDITION_4,
	ISNULL(cte.FMH_ES_MH_Cond_5, '') AS MENTAL_HEALTH_CONDITION_5,
	ISNULL(cte.FMH_ES_HONOS_START, '') AS HONOS_SCORE_AT_COMMENCEMENT,
	ISNULL(cte.FMH_ES_HONOS_END, '') AS HONOS_SCORE_ON_DISCHARGE,
	ISNULL(cte.FMH_ES_TOB_COM, 8) AS TOBACCO_USE_AT_COMMENCEMENT,
	ISNULL(cte.FMH_ES_TOB_END, 8) AS TOBACCO_USE_ON_DISCHARGE,
	ISNULL(REPLACE(CONVERT(VARCHAR, cte.FMH_ES_End_Date,103),'/',''),'') AS DISCHARGE_DATE,
	ISNULL(cte.FMH_ES_Dis_Reason,'') AS DISCHARGE_REASON

FROM CTE 
	Inner Join ClientEvents CE WITH (NOLOCK)on CE.evID=CTE.respParent
	INNER JOIN Programs WITH (NOLOCK) ON CE.evProgramID = Programs.pgID
	INNER JOIN Episode WITH (NOLOCK) ON ce.epID = Episode.epID

WHERE ce.evRevokeDate IS NULL
-- AND (Programs.pgEnd IS NULL OR Programs.pgEnd >= '2018-07-01')